name: ${project.name}
main: de.themoep.timedscripts.TimedScripts
version: '${minecraft.plugin.version}'
description: ${project.description}
authors: [Phoenix616]
commands:
   timedscripts:
      aliases: [scripts]
      description: Main plugin command for adminstrative purposes
      usage: /<command> [reload [stop]|stop]
      permission: TimedScripts.command
      permission-message: You don't have the permission <permission>
   timedscript:
      aliases: [script]
      description: Command to run and edit scripts
      usage: /<command> <help|create|edit|run|info|view|save|delete>
      permission: TimedScripts.command
      permission-message: You don't have the permission <permission>
permissions:
   TimedScripts.admin:
      description: Gives permission to the admin command
      default: false
   TimedScripts.command:
      description: Gives permission to the /script command
      default: false
   TimedScripts.command.edit:
      description: Gives permission to edit scripts
      default: false
   TimedScripts.command.edit.others:
      description: Gives permission to edit scripts by other people
      default: false
   TimedScripts.command.run:
      description: Gives permission to run scripts
      default: false
   TimedScripts.command.runasother:
      description: Gives permission to start scripts as an other player
      default: false
   TimedScripts.command.runasconsole:
      description: Gives permission to start scripts as the console
      default: false
   TimedScripts.command.create:
      description: Gives permission to create new scripts
      default: false
   TimedScripts.command.save:
      description: Gives permission to save a script
      default: false
   TimedScripts.command.info:
      description: Gives permission to get info about scripts
      default: false
   TimedScripts.command.view:
      description: Gives permission to view the commands of scripts
      default: false
   TimedScripts.command.delete:
      description: Gives permission to delete scripts
      default: false
