name: ${project.name}
main: de.themoep.timedscripts.TimedScripts
version: '${minecraft.plugin.version}'
api-version: 1.13
description: ${project.description}
authors: [Phoenix616]
commands:
   timedscripts:
      aliases: [scripts]
      description: Main plugin command for adminstrative purposes
      usage: /<command> [load|reload|stop] [<script>]
      permission: timedscripts.command
      permission-message: You don't have the permission <permission>
   timedscript:
      aliases: [script]
      description: Command to run and edit scripts
      usage: /<command> <help|create|edit|run|info|view|save|delete|stop|reload>
      permission: timedscripts.command
      permission-message: You don't have the permission <permission>
permissions:
   timedscripts.admin:
      description: Gives permission to the admin command
      default: false
   timedscripts.command:
      description: Gives permission to the /script command
      default: op
   timedscripts.command.edit:
      description: Gives permission to edit scripts
      default: false
   timedscripts.command.edit.others:
      description: Gives permission to edit scripts by other people
      default: false
   timedscripts.command.run:
      description: Gives permission to run scripts
      default: false
   timedscripts.command.runasother:
      description: Gives permission to start scripts as an other player
      default: false
   timedscripts.command.runasconsole:
      description: Gives permission to start scripts as the console
      default: false
   timedscripts.command.create:
      description: Gives permission to create new scripts
      default: false
   timedscripts.command.save:
      description: Gives permission to save a script
      default: false
   timedscripts.command.info:
      description: Gives permission to get info about scripts
      default: false
   timedscripts.command.view:
      description: Gives permission to view the commands of scripts
      default: false
   timedscripts.command.delete:
      description: Gives permission to delete scripts
      default: false
   timedscripts.command.stop:
      description: Gives permission to stop scripts
      default: false
   timedscripts.command.reload:
      description: Gives permission to reload scripts
      default: false
